# Generated by Django 4.1 on 2022-08-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cleoyogaapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posecard",
            old_name="sanskirt_name",
            new_name="sanskrit_name",
        ),
    ]
